apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: namespace-workflow-1762246169610
  labels:
    app.kubernetes.io/name: myapp
    kubernetes.azure.com/generator: devhub
data: