spring:
  application:
    name: book-service
  cloud:
    azure:
      storage:
        account-name: myappdemoblob
        account-key: ${BLOB_ACCOUNT_KEY}
        endpoint: https://myappdemoblob.blob.core.windows.net

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://azurelearnindbserverdemo.database.windows.net:1433;database=DemoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging.level.com.romankudryashov.eventdrivenarchitecture: debug

inbox:
  processing:
    task:
      cron: "*/5 * * * * *"
      batch.size: 50
      subtask.timeout: 10000

user.check.use-streaming-data: false

azure:
  servicebus:
    queue-name: bookingservicequeue
    connection-string: ${SERVICE_BUS_CONNECTION_STRING}
