spring:
  application:
    name: book-service
  cloud:
    azure:
      storage:
        account-name: myappdemoblob
        account-key: ${BLOB_ACCOUNT_KEY}
        endpoint: https://myappdemoblob.blob.core.windows.net

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://myapp.postgres.database.azure.com:5432/postgres
    username: ${PGUSER}
    password: ${PGPASSWORD}

logging.level.com.romankudryashov.eventdrivenarchitecture: debug

inbox:
  processing:
    task:
      cron: "*/5 * * * * *"
      batch.size: 50
      subtask.timeout: 10000

user.check.use-streaming-data: false
